# Generated by Django 3.1.7 on 2021-04-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_short',
            field=models.TextField(default='Template Short Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='Template Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.TextField(default='Template Title'),
        ),
    ]
