# Generated by Django 3.1.7 on 2021-04-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210420_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description_short',
            new_name='descriptionShort',
        ),
        migrations.AddField(
            model_name='product',
            name='imageMain',
            field=models.ImageField(default='img/norm_def.png', height_field=1200, upload_to='img/', width_field=630),
        ),
        migrations.AddField(
            model_name='product',
            name='imagePreview',
            field=models.ImageField(default='img/small_def.png', height_field=600, upload_to='img/', width_field=315),
        ),
    ]
