# Generated by Django 3.1.7 on 2021-04-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210420_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default='Template Title', max_length=120),
        ),
    ]
