# Generated by Django 3.2 on 2021-04-22 12:52

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210422_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='attributes',
            field=models.JSONField(default=store.models.Product.default_json, null=True, verbose_name='Attributes'),
        ),
    ]
