# Generated by Django 3.2 on 2021-04-22 16:43

from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_attributes_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='attributes',
            field=models.JSONField(blank=True, default=store.models.Product.default_json, null=True, verbose_name='Attributes'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subCathegoryFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.subcathegory'),
        ),
    ]
